/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/financials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProjectFinancials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description NOT YET LIVE. Intended Ecobank sandbox payment-verification endpoint. */
        post: operations["verifyEcobankPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        /** @description NOT YET LIVE. Intended lookup for an Ecobank verification result. */
        get: operations["getPaymentVerification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        DashboardSummary: {
            cashPosition: number;
            owed: number;
            dueThisWeek: number;
            activeProjects: number;
            cashGap: number;
        };
        CreativeProfile: {
            id: string;
            businessName: string;
            craft: string;
            location: string;
            ownerName: string;
            projectsCompleted: number;
            averageProjectValue: number;
            typicalDepositPct: number;
            averagePaymentDelayDays: number;
            averageMaterialOverrunPct: number;
            averageMarginPct: number;
        };
        ProjectCost: {
            id: string;
            label: string;
            /** @enum {string} */
            category: "materials" | "labour" | "transport" | "other";
            amount: number;
            /** @enum {string} */
            fundedBy: "creator" | "client";
            paidOnDay: number;
        };
        ActivityEvent: {
            id: string;
            label: string;
            /** Format: date-time */
            timestamp: string;
        };
        Project: {
            id: string;
            name: string;
            clientId: string;
            clientName: string;
            craft: string;
            revenue: number;
            depositPct: number;
            costs: components["schemas"]["ProjectCost"][];
            expectedPaymentDays: number;
            /** @enum {string} */
            status: "active" | "awaiting_payment" | "completed";
            /** Format: date-time */
            createdAt: string;
            activity: components["schemas"]["ActivityEvent"][];
        };
        Client: {
            id: string;
            name: string;
            projectIds: string[];
            totalBilled: number;
            totalPaid: number;
            averagePaymentDays: number;
        };
        CashFlowPoint: {
            label: string;
            /** Format: date */
            date: string;
            projectedBalance: number;
            inflow: number;
            outflow: number;
        };
        ForecastResponse: {
            points: components["schemas"]["CashFlowPoint"][];
        };
        DaysToCash: {
            /** @constant */
            status: "planned";
            days: number;
        } | {
            /** @constant */
            status: "pending";
            daysSoFar: number;
        } | {
            /** @constant */
            status: "complete";
            days: number;
        };
        ProjectFinancialSnapshot: {
            depositAmount: number;
            upfrontExposure: number;
            cashGap: number;
            expectedProfit: number;
            profitMarginPct: number;
            daysToCash: components["schemas"]["DaysToCash"];
            cashFlow: components["schemas"]["CashFlowPoint"][];
            /** Format: date */
            gapDate: string | null;
        };
        Feedback: {
            id: string;
            name: string;
            craft: string;
            location: string;
            quote: string;
            avatar: string;
            verified: boolean;
            source: string;
            /** Format: date-time */
            date: string;
        };
        PaymentVerificationRequest: {
            paymentReference: string;
            invoiceId?: string;
            amount: number;
            /** @constant */
            currency: "NGN";
        };
        PaymentVerificationResponse: {
            paymentReference: string;
            /** @enum {string} */
            status: "pending" | "verified" | "failed";
            amount: number;
            /** @constant */
            currency: "NGN";
            /** Format: date-time */
            verifiedAt?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ProjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects visible to the current workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectFinancials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computed financial snapshot for a project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFinancialSnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clients visible to the current workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projected cash-flow points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    listFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feedback shown on the public landing page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"][];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current creative profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeProfile"];
                };
            };
        };
    };
    verifyEcobankPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentVerificationRequest"];
            };
        };
        responses: {
            /** @description NOT YET LIVE. Verification result from the payment rail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentVerificationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description NOT YET LIVE. Payment provider unavailable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPaymentVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NOT YET LIVE. Payment verification result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentVerificationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
