"""provider-agnostic payments: virtual accounts, provider events, reconciliation

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 09:52:22.869759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('amount_kobo', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_provider_event')
    )
    op.create_index(op.f('ix_provider_events_reference'), 'provider_events', ['reference'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('first_run_id', sa.String(), nullable=False),
    sa.Column('last_run_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('internal_key', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('external_account', sa.String(), nullable=True),
    sa.Column('external_amount_kobo', sa.BigInteger(), nullable=True),
    sa.Column('external_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delta_kobo', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_fingerprint'), 'reconciliation_items', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_owner_id'), 'reconciliation_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_project_id'), 'reconciliation_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_provider'), 'reconciliation_items', ['provider'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('internal_count', sa.Integer(), nullable=False),
    sa.Column('external_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('discrepancy_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('balanced', sa.Boolean(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_provider'), 'reconciliation_runs', ['provider'], unique=False)
    op.create_table('virtual_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('expected_amount_kobo', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'account_number', name='uq_va_provider_number'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_virtual_accounts_account_number'), 'virtual_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_virtual_accounts_project_id'), 'virtual_accounts', ['project_id'], unique=False)
    op.add_column('payments', sa.Column('provider_ref', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('virtual_account_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.add_column('payouts', sa.Column('provider_ref', sa.String(), nullable=True))
    op.add_column('payouts', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payout_bank_code', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payout_account_number', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payout_account_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('payout_account_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'payout_account_verified')
    op.drop_column('profiles', 'payout_account_name')
    op.drop_column('profiles', 'payout_account_number')
    op.drop_column('profiles', 'payout_bank_code')
    op.drop_column('payouts', 'failure_reason')
    op.drop_column('payouts', 'provider_ref')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_column('payments', 'reconciled_at')
    op.drop_column('payments', 'virtual_account_id')
    op.drop_column('payments', 'provider_ref')
    op.drop_index(op.f('ix_virtual_accounts_project_id'), table_name='virtual_accounts')
    op.drop_index(op.f('ix_virtual_accounts_account_number'), table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    op.drop_index(op.f('ix_reconciliation_runs_provider'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_items_provider'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_project_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_owner_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_fingerprint'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_provider_events_reference'), table_name='provider_events')
    op.drop_table('provider_events')
    # ### end Alembic commands ###
